/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class VentanaVentas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVentas
     */
    public VentanaVentas() {
        initComponents();
        setTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblLibro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblTotal = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtMontoTotal = new javax.swing.JTextField();
        lblTotal1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblTotal2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtCambio = new javax.swing.JTextField();
        lblPagar = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 15, 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setBackground(new java.awt.Color(15, 15, 20));
        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(252, 213, 68));
        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtLibro.setEditable(false);
        txtLibro.setBackground(new java.awt.Color(15, 15, 20));
        txtLibro.setForeground(new java.awt.Color(252, 213, 68));
        txtLibro.setText("Ingrese su nombre");
        txtLibro.setBorder(null);
        txtLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroActionPerformed(evt);
            }
        });
        jPanel1.add(txtLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, 20));

        jSeparator3.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator3.setForeground(new java.awt.Color(252, 213, 68));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 280, 10));

        lblLibro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLibro.setForeground(new java.awt.Color(252, 213, 68));
        lblLibro.setText("Titulo del libro");
        jPanel1.add(lblLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, 20));

        jSeparator1.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator1.setForeground(new java.awt.Color(252, 213, 68));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 280, 10));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(15, 15, 20));
        txtNombre.setForeground(new java.awt.Color(252, 213, 68));
        txtNombre.setText("Ingrese su nombre");
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, 20));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(252, 213, 68));
        lblFecha.setText("Fecha de Entrega");
        lblFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jSeparator2.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator2.setForeground(new java.awt.Color(252, 213, 68));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 280, 10));

        jDateChooser1.setBackground(new java.awt.Color(15, 15, 20));
        jDateChooser1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(252, 213, 68));
        lblTotal.setText("Monto Total");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator4.setForeground(new java.awt.Color(252, 213, 68));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 10));

        txtMontoTotal.setEditable(false);
        txtMontoTotal.setBackground(new java.awt.Color(15, 15, 20));
        txtMontoTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMontoTotal.setForeground(new java.awt.Color(252, 213, 68));
        txtMontoTotal.setText("Ingrese monto total");
        txtMontoTotal.setBorder(null);
        jPanel1.add(txtMontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 23));

        lblTotal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal1.setForeground(new java.awt.Color(252, 213, 68));
        lblTotal1.setText("Total a pagar");
        jPanel1.add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, -1));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(15, 15, 20));
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(252, 213, 68));
        txtTotal.setText("Ingrese monto total");
        txtTotal.setBorder(null);
        txtTotal.setOpaque(false);
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, 23));

        jSeparator5.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator5.setForeground(new java.awt.Color(252, 213, 68));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 280, 10));

        lblTotal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal2.setForeground(new java.awt.Color(252, 213, 68));
        lblTotal2.setText("Cambio");
        jPanel1.add(lblTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, -1));

        jSeparator6.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator6.setForeground(new java.awt.Color(252, 213, 68));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 280, 10));

        txtCambio.setEditable(false);
        txtCambio.setBackground(new java.awt.Color(15, 15, 20));
        txtCambio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCambio.setForeground(new java.awt.Color(252, 213, 68));
        txtCambio.setText("Cambio");
        txtCambio.setBorder(null);
        txtCambio.setOpaque(false);
        jPanel1.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 140, 23));

        lblPagar.setBackground(new java.awt.Color(252, 213, 68));
        lblPagar.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        lblPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagar.setText("Pagar");
        lblPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPagar.setOpaque(true);
        lblPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPagarMouseClicked(evt);
            }
        });
        jPanel1.add(lblPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 350, 510));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menú 21x29.7 сm.gif"))); // NOI18N
        lblFondo.setText("jLabel2");
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 610, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void lblPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagarMouseClicked
       // Crear();
       // String n=txtNombre.getText();
       // String c=txtCedula.getText();
       // String num=txtTelefono.getText();
        /*
        if(n.equals("")){
            showMessageDialog(this,"Nombre vacio"); lblNombre.setForeground(Color.red);
            txtNombre.requestFocus();return;
        }else lblNombre.setForeground(Color.black);
        //-------------------------------------------------------------
        if(c.equals("")){
            showMessageDialog(this,"Cedula vacia"); lblCedula.setForeground(Color.red);
            txtCedula.requestFocus();return;
        }else lblCedula.setForeground(Color.black);
        //-------------------------------------------------------------
        if(num.equals("")){
            showMessageDialog(this,"Telefono vacio"); lblTelefono.setForeground(Color.red);
            txtTelefono.requestFocus();return;
        }else lblTelefono.setForeground(Color.black);
        */

        //C[p++]=new Cliente(Integer.parseInt(c),num,n);
        //Object O []=new Object [3]; O[0]=n; O[1]=c; O[2]=num;
        //m.addRow(O);
        //txtNombre.setText("");txtTelefono.setText("");txtCedula.setText("");
    }//GEN-LAST:event_lblPagarMouseClicked
    private void setTexto(){
        double total=P[p++].getMontoTotal()*P[p++].getCantidaLibros();
        double cambio=P[p++].getMontoTotal()-total;
        txtNombre.setText(C[c++].getNombre());
        txtLibro.setText(L[c++].getTitulo());
        txtMontoTotal.setText(P[p++].getMontoTotal()+"");
        txtTotal.setText(total+"");
        txtCambio.setText(cambio+"");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVentas().setVisible(true);
            }
        });
    }
    int l=0;
    int c=0;
    int p=0;
    private Libro L[]=new Libro[10];
    private Cliente C[ ]=new Cliente[1000];
    private Pedido P[ ]=new Pedido[1000];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
