
import javax.swing.JOptionPane;
import rojerusan.RSAnimation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpControlPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblLineaA = new javax.swing.JLabel();
        lblLineaB = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblLineaC = new javax.swing.JLabel();
        lblSelectInicio = new javax.swing.JLabel();
        lblSelectCliente = new javax.swing.JLabel();
        lblSelectLibro = new javax.swing.JLabel();
        lblSelectComprar = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblComprar = new javax.swing.JLabel();
        lblLibros = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpBackground = new javax.swing.JPanel();
        lblMinimizar1 = new javax.swing.JLabel();
        lblSalir1 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 500));

        jpControlPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpControlPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Libro.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpControlPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 50, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flacha.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jpControlPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Venta.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpControlPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 50, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 40));

        lblLineaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/line2.png"))); // NOI18N
        jpControlPanel.add(lblLineaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 275, 160, 10));

        lblLineaB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/line2.png"))); // NOI18N
        jpControlPanel.add(lblLineaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 388, 160, 10));

        lblLinea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/line2.png"))); // NOI18N
        jpControlPanel.add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, 10));

        lblLineaC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/line2.png"))); // NOI18N
        jpControlPanel.add(lblLineaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 10));

        lblSelectInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSelectInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSelectInicioMouseClicked(evt);
            }
        });
        jpControlPanel.add(lblSelectInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 110, 60));

        lblSelectCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSelectCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSelectClienteMouseClicked(evt);
            }
        });
        jpControlPanel.add(lblSelectCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 60));

        lblSelectLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSelectLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSelectLibroMouseClicked(evt);
            }
        });
        jpControlPanel.add(lblSelectLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 229, 230, 53));

        lblSelectComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSelectComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSelectComprarMouseClicked(evt);
            }
        });
        jpControlPanel.add(lblSelectComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 55));

        lblInicio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 204, 51));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");
        jpControlPanel.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, 130, 30));

        lblComprar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblComprar.setForeground(new java.awt.Color(255, 204, 51));
        lblComprar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComprar.setText("Comprar");
        jpControlPanel.add(lblComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 130, 30));

        lblLibros.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblLibros.setForeground(new java.awt.Color(255, 204, 51));
        lblLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLibros.setText("Libros");
        jpControlPanel.add(lblLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        lblCliente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 204, 51));
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("Clientes");
        jpControlPanel.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PANEL.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jpControlPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 497));

        getContentPane().add(jpControlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 2, 230, 497));

        jpBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        lblMinimizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizar1MouseClicked(evt);
            }
        });
        jpBackground.add(lblMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        lblSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Delete_32px.png"))); // NOI18N
        lblSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalir1MouseClicked(evt);
            }
        });
        jpBackground.add(lblSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login_1.png"))); // NOI18N
        jpBackground.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jpBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizar1MouseClicked
        this.setState(VentanaPrincipal.ICONIFIED);
    }//GEN-LAST:event_lblMinimizar1MouseClicked

    private void lblSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalir1MouseClicked
        try{
            int dialogButton= JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "Desea cerra el sistema?","EXIT",dialogButton);
            if(result==0){
                System.exit(0);
            }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }//GEN-LAST:event_lblSalir1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        RSAnimation.setMoverIzquierda(0, -180, 10, 5, jpControlPanel);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        RSAnimation.setMoverDerecha(-180, 0, 10, 5, jpControlPanel); 
    }//GEN-LAST:event_jLabel7MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblLinea.setVisible(true);
        lblLineaA.setVisible(false);
        lblLineaB.setVisible(false);
        lblLineaC.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void lblSelectClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectClienteMouseClicked
        lblLinea.setVisible(false);
        lblLineaA.setVisible(false);
        lblLineaB.setVisible(false);
        lblLineaC.setVisible(true);
        
    }//GEN-LAST:event_lblSelectClienteMouseClicked

    private void lblSelectLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectLibroMouseClicked
        lblLinea.setVisible(false);
        lblLineaA.setVisible(true);
        lblLineaB.setVisible(false);
        lblLineaC.setVisible(false);
    }//GEN-LAST:event_lblSelectLibroMouseClicked

    private void lblSelectComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectComprarMouseClicked
        lblLinea.setVisible(false);
        lblLineaA.setVisible(false);
        lblLineaB.setVisible(true);
        lblLineaC.setVisible(false);
    }//GEN-LAST:event_lblSelectComprarMouseClicked

    private void lblSelectInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectInicioMouseClicked
        lblLinea.setVisible(true);
        lblLineaA.setVisible(false);
        lblLineaB.setVisible(false);
        lblLineaC.setVisible(false);
    }//GEN-LAST:event_lblSelectInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpBackground;
    private javax.swing.JPanel jpControlPanel;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblComprar;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblLibros;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblLineaA;
    private javax.swing.JLabel lblLineaB;
    private javax.swing.JLabel lblLineaC;
    private javax.swing.JLabel lblMinimizar1;
    private javax.swing.JLabel lblSalir1;
    private javax.swing.JLabel lblSelectCliente;
    private javax.swing.JLabel lblSelectComprar;
    private javax.swing.JLabel lblSelectInicio;
    private javax.swing.JLabel lblSelectLibro;
    // End of variables declaration//GEN-END:variables
}
