
import java.awt.Color;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class VentanaPedido extends javax.swing.JFrame{

    /**
     * Creates new form Pedido
     */
    public VentanaPedido() {
        initComponents();
        this.setLocationRelativeTo(null); 
        m=(DefaultTableModel) tblLibros.getModel();
        leerCliente();leerLibro();
       // agregaLibro();
        txtFecha.setText(fecha());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        lblCantidad = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblPagar = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtEdicion = new javax.swing.JTextField();
        lblLibro = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        cmbTitulo = new javax.swing.JComboBox<>();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        lblCedula = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        cmbCedula = new javax.swing.JComboBox<>();
        lblVolver = new javax.swing.JLabel();
        cbxEfectivo = new javax.swing.JCheckBox();
        cbxCredito = new javax.swing.JCheckBox();
        lblSalir1 = new javax.swing.JLabel();
        lblMinimizar1 = new javax.swing.JLabel();
        lblBackground1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(15, 15, 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setOpaque(false);
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(252, 213, 68));
        lblCantidad.setText("CANTIDAD");
        pnlPrincipal.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(252, 213, 68));
        lblFecha.setText("FECHA ENTREGA");
        lblFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPrincipal.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        lblPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPago.setForeground(new java.awt.Color(252, 213, 68));
        lblPago.setText("PAGÓ");
        pnlPrincipal.add(lblPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(252, 213, 68));
        lblTotal.setText("MONTO TOTAL");
        pnlPrincipal.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(15, 15, 20));
        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(252, 211, 114));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 140, 23));

        txtCantidad.setBackground(new java.awt.Color(15, 15, 20));
        txtCantidad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(252, 211, 114));
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadMouseClicked(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });
        pnlPrincipal.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, 23));

        jSeparator1.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator1.setForeground(new java.awt.Color(252, 213, 68));
        pnlPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, 10));

        jSeparator2.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator2.setForeground(new java.awt.Color(252, 213, 68));
        pnlPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 280, 10));

        jSeparator3.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator3.setForeground(new java.awt.Color(252, 213, 68));
        pnlPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 280, 10));

        jSeparator4.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator4.setForeground(new java.awt.Color(252, 213, 68));
        pnlPrincipal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 280, 10));

        lblPagar.setBackground(new java.awt.Color(252, 213, 68));
        lblPagar.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        lblPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagar.setText("Pagar");
        lblPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPagar.setOpaque(true);
        lblPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPagarMouseClicked(evt);
            }
        });
        pnlPrincipal.add(lblPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 100, 30));

        txtTotal.setBackground(new java.awt.Color(15, 15, 20));
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(252, 211, 114));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalMouseClicked(evt);
            }
        });
        pnlPrincipal.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, 23));

        jPanel2.setBackground(new java.awt.Color(15, 15, 20));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator5.setForeground(new java.awt.Color(252, 213, 68));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 280, 10));

        jSeparator6.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator6.setForeground(new java.awt.Color(252, 213, 68));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 280, 10));

        jSeparator8.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator8.setForeground(new java.awt.Color(252, 213, 68));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, 10));

        txtEdicion.setEditable(false);
        txtEdicion.setBackground(new java.awt.Color(15, 15, 20));
        txtEdicion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtEdicion.setForeground(new java.awt.Color(252, 211, 114));
        txtEdicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdicion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicionActionPerformed(evt);
            }
        });
        jPanel2.add(txtEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 200, 20));

        lblLibro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLibro.setForeground(new java.awt.Color(252, 213, 68));
        lblLibro.setText("TITULO");
        jPanel2.add(lblLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, -1));

        lblAutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAutor.setForeground(new java.awt.Color(252, 213, 68));
        lblAutor.setText("AUTOR");
        jPanel2.add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 20));

        lblEdicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEdicion.setForeground(new java.awt.Color(252, 213, 68));
        lblEdicion.setText("EDICION");
        jPanel2.add(lblEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, -1));

        txtAutor.setEditable(false);
        txtAutor.setBackground(new java.awt.Color(15, 15, 20));
        txtAutor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtAutor.setForeground(new java.awt.Color(252, 211, 114));
        txtAutor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        jPanel2.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 200, 20));

        cmbTitulo.setBackground(new java.awt.Color(252, 213, 68));
        cmbTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbTitulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTituloItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 200, 20));

        lblCosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(252, 213, 68));
        lblCosto.setText("COSTO");
        jPanel2.add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        txtCosto.setEditable(false);
        txtCosto.setBackground(new java.awt.Color(15, 15, 20));
        txtCosto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtCosto.setForeground(new java.awt.Color(252, 211, 114));
        txtCosto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCosto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 200, 20));

        jSeparator11.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator11.setForeground(new java.awt.Color(252, 213, 68));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, 10));

        pnlPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 380, 190));

        tblLibros.setBackground(new java.awt.Color(255, 204, 0));
        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Edicion", "Costo"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        pnlPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 470, 130));

        lblCedula.setBackground(new java.awt.Color(15, 15, 20));
        lblCedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(252, 213, 68));
        lblCedula.setText("Cedula");
        pnlPrincipal.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 50, 20));

        jSeparator7.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator7.setForeground(new java.awt.Color(252, 213, 68));
        pnlPrincipal.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, 10));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(15, 15, 20));
        txtNombre.setForeground(new java.awt.Color(252, 213, 68));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        pnlPrincipal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 170, 20));

        lblNombre.setBackground(new java.awt.Color(15, 15, 20));
        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(252, 213, 68));
        lblNombre.setText("Nombre");
        pnlPrincipal.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 20));

        jSeparator9.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator9.setForeground(new java.awt.Color(252, 213, 68));
        pnlPrincipal.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, 10));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(15, 15, 20));
        txtTelefono.setForeground(new java.awt.Color(252, 213, 68));
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        pnlPrincipal.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 170, 20));

        lblTelefono.setBackground(new java.awt.Color(15, 15, 20));
        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(252, 213, 68));
        lblTelefono.setText("Telefono");
        pnlPrincipal.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(252, 213, 68));
        jSeparator10.setForeground(new java.awt.Color(252, 213, 68));
        pnlPrincipal.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 280, 10));

        cmbCedula.setBackground(new java.awt.Color(252, 213, 68));
        cmbCedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbCedula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCedulaItemStateChanged(evt);
            }
        });
        cmbCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCedulaActionPerformed(evt);
            }
        });
        pnlPrincipal.add(cmbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 170, -1));

        lblVolver.setBackground(new java.awt.Color(252, 213, 68));
        lblVolver.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        lblVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolver.setText("Volver");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.setOpaque(true);
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });
        pnlPrincipal.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 100, 30));

        cbxEfectivo.setForeground(new java.awt.Color(252, 213, 68));
        cbxEfectivo.setText("Efectivo");
        cbxEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEfectivoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(cbxEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        cbxCredito.setForeground(new java.awt.Color(252, 213, 68));
        cbxCredito.setText("Credito");
        cbxCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCreditoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(cbxCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        lblSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Delete_32px.png"))); // NOI18N
        lblSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalir1MouseClicked(evt);
            }
        });
        getContentPane().add(lblSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        lblMinimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        lblMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizar1MouseClicked(evt);
            }
        });
        getContentPane().add(lblMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        lblBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login_1.png"))); // NOI18N
        getContentPane().add(lblBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static boolean isNumeric(String cadena){
            try {
                    Integer.parseInt(cadena);
                    return true;
            } catch (NumberFormatException nfe){
                    return false;
            }
    }
    private void Pago(){
        String cantidad=txtCantidad.getText();
        String montototal=txtTotal.getText();
        double total=0;
        double cambio=0;
        int ia=cmbCedula.getSelectedIndex();
        int it=cmbTitulo.getSelectedIndex();
        String costo=txtTotal.getText();
        String nombre=txtNombre.getText();
        String telefono=txtTelefono.getText();
        String autor=txtAutor.getText();
        String edicion=txtEdicion.getText();
        String fecha=txtFecha.getText();
        
        
        if(cantidad.equals("")){
            showMessageDialog(this,"Cantidad Vacia");lblCantidad.setForeground(Color.red);
            txtCantidad.requestFocus();return; 
            } 
        
            if(montototal.equals("")){
            showMessageDialog(this,"Monto total vacio");lblTotal.setForeground(Color.red);
            txtTotal.requestFocus();return;
            }
            
        try{
            int cant=Integer.parseInt(cantidad);

            
        }catch (NumberFormatException ex){
            showMessageDialog(null,"Solo numeros"); txtCantidad.setText("");
        }
        try{
           
            double cost=Double.parseDouble(montototal);
            
            
            
        }catch (NumberFormatException ex){
            showMessageDialog(null,"Solo numeros"); txtTotal.setText("");
        }
        if ((cbxCredito.isSelected()==false)&&(cbxEfectivo.isSelected()==false)){
            cbxCredito.setForeground(Color.red);
            cbxEfectivo.setForeground(Color.red);
            showMessageDialog(null,"Selecciona una opción","Alerta",2); return;
        } 
        
            total=Double.parseDouble(txtCosto.getText())*Double.parseDouble(txtCantidad.getText());
            if(total > Double.parseDouble(costo)){
            showMessageDialog(null,"Monto insuficiente"); 
            lblTotal.setForeground(Color.red); txtTotal.setText("");
            }else 
            cambio=Double.parseDouble(txtTotal.getText())-total;
            if(total < Double.parseDouble(costo))
            showMessageDialog(null,"Pago realizado"); 
            
            txtCantidad.setText("");txtTotal.setText("");
        
        try { //Flujo de caracteres para salida (escritura)
            java.io.FileWriter fcs=new java.io.FileWriter("VENTAS.TXT");
            String cad="";
  
            String R[]=new String[13];
            R[0]=txtNombre.getText();R[1]=txtTelefono.getText();R[2]=(String) cmbCedula.getSelectedItem();R[3]=(String) cmbTitulo.getSelectedItem();
            R[4]=txtAutor.getText();R[5]=txtEdicion.getText();R[6]=txtCosto.getText();R[7]=txtTotal.getText();
            R[8]=txtCantidad.getText();R[9]=tipo;R[11]=fecha();
            V[v++]=new Ventas(nombre, telefono,ia,it,  autor,  edicion,costo, montototal,  cantidad, total,tipo,fecha, cambio);
            for (int i = 0; i < v; i++){
                //cad=cad+"Nombre:"+C[i].getNombre()+"|"+"Telefono:"+C[i].getTelefono()+"|"+"Cedula:"+C[i].getCedula()+"\n"; 
                cad=cad+"Nombre:"+C[i].getNombre()+"|"+"Telefono:"+C[i].getTelefono()+"|"+"Cedula:"+C[ia].getCedula()+"\n"
                +"Titulo del libro: "+L[it].getTitulo()+"|"+"Autor: "+L[i].getAutor()+"|"+"Edición: "+L[i].getEdicion()+"\n"
                +"Costo: "+txtCosto.getText()+"|"+"Pago: "+txtTotal.getText()+"|"+"Cantidad: "+V[i].getCantidad()+"|"+"Total: "+total+"\n"
                +"Tipo de pago: "+tipo+"|"+"Fecha: "+fecha()+"|"+"Cambio: "+cambio+"\n"+"_______________________________________________________________ \n";
            
            }
            fcs.write(cad);fcs.flush(); 
        }catch (FileNotFoundException ex) {  }
         catch (IOException ex) {        }
    }
    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void lblPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagarMouseClicked
     Pago();
    }//GEN-LAST:event_lblPagarMouseClicked

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicionActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
       
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if(evt.getKeyCode()==VK_ENTER) txtTelefono.requestFocus();
    }//GEN-LAST:event_txtNombreKeyPressed

    private void cmbCedulaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCedulaItemStateChanged
       int i=cmbCedula.getSelectedIndex();
       txtNombre.setText(C[i].getNombre());txtTelefono.setText(C[i].getTelefono()+"");
       
    }//GEN-LAST:event_cmbCedulaItemStateChanged

    private void cmbTituloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTituloItemStateChanged
       int i=cmbTitulo.getSelectedIndex();
       txtAutor.setText(L[i].getAutor());txtEdicion.setText(L[i].getEdicion()+"");txtCosto.setText(L[i].getCosto()+"");
    }//GEN-LAST:event_cmbTituloItemStateChanged

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        if(evt.getKeyCode()==VK_ENTER); //agregaLibro();
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_lblVolverMouseClicked

    private void cmbCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCedulaActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void cbxCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCreditoActionPerformed
        if (cbxCredito.isSelected()==true)cbxEfectivo.setEnabled(false);cbxCredito.setForeground(Color.yellow);cbxEfectivo.setForeground(Color.yellow);
        if (cbxCredito.isSelected()==false)cbxEfectivo.setEnabled(true);
        if (cbxCredito.isSelected()==true)tipo="C";
        if (cbxCredito.isSelected()==false)tipo="";
    }//GEN-LAST:event_cbxCreditoActionPerformed

    private void cbxEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEfectivoActionPerformed
        if (cbxEfectivo.isSelected()==true)cbxCredito.setEnabled(false);cbxCredito.setForeground(Color.yellow);cbxEfectivo.setForeground(Color.yellow);
        if (cbxEfectivo.isSelected()==false)cbxCredito.setEnabled(true);
        if (cbxEfectivo.isSelected()==true)tipo="E";
        if (cbxEfectivo.isSelected()==false)tipo="";
    }//GEN-LAST:event_cbxEfectivoActionPerformed

    private void txtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseClicked
        txtCantidad.setText("");
    }//GEN-LAST:event_txtCantidadMouseClicked

    private void txtTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseClicked
        txtTotal.setText("");
    }//GEN-LAST:event_txtTotalMouseClicked

    private void lblSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalir1MouseClicked
        try{
            int dialogButton= JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "Desea cerra el sistema?","EXIT",dialogButton);
            if(result==0){
            System.exit(0);
            }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }//GEN-LAST:event_lblSalir1MouseClicked

    private void lblMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizar1MouseClicked
        this.setState(VentanaPrincipal.ICONIFIED);
    }//GEN-LAST:event_lblMinimizar1MouseClicked

    private void leerCliente(){
            try {  
            java.io.FileReader fce=new java.io.FileReader("CLIENTES.TXT");
            java.io.BufferedReader be=new java.io.BufferedReader(fce);
            String linea="";
            
            while(   (linea=be.readLine())  !=null ){
                String R[]=linea.split("\\|"); 
                C[p++]=new Cliente(R[0],R[1],R[2]);
                cmbCedula.addItem(R[0]);
            }
        } catch (FileNotFoundException ex) {
        
        } catch (IOException ex) {
          
        } catch (NullPointerException ex) {
            
        }
        
    }
    private void leerLibro(){
            try {  
            java.io.FileReader fce=new java.io.FileReader("LIBROS.TXT");
            java.io.BufferedReader be=new java.io.BufferedReader(fce);
            String linea="";
            
            while(   (linea=be.readLine())  !=null ){
                String R[]=linea.split("\\|"); m.addRow(R);
                L[l++]=new Libro(R[0],R[1],R[2],Double.parseDouble(R[3]));
                cmbTitulo.addItem(R[0]);
            }
        } catch (FileNotFoundException ex) {
        
        }
          catch (IOException ex) {
          
        }
        
    }
    private String fecha(){
        
        Date fecha = new Date();   
        SimpleDateFormat fechaentrega = new SimpleDateFormat ("dd/MM/YYYY");
        return fechaentrega.format(fecha);
    }
    

    
    /*private void agregaLibro(){
        
        String R[]=new String[4];
        int ic=cmbCedula.getSelectedIndex(); int il=cmbTitulo.getSelectedIndex();
        R[0]=L[il].getTitulo();//R[1]=L[il].getEdicion();
        try{   
        int cant=Integer.parseInt(txtCantidad.getText());
        int costo=cant*100;
        int total=0;
        R[1]=txtAutor.getText()+"";R[2]=txtEdicion.getText()+"";R[3]=txtCosto.getText();
        txtTotal.setText(costo+"");
        m.addRow(R);
        }catch(NumberFormatException ex){
            txtCantidad.setText("");txtCantidad.requestFocus();return;
        }
        
        
        
        
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPedido().setVisible(true);
            }
        });
    }
    private String tipo="";
    Pedido pe=new Pedido();
    private Libro L[]=new Libro[1000];
    private int l=0; 
    private Cliente C[ ]=new Cliente[100];
    private int p=0;
    private DefaultTableModel m;
    Recibo r= new Recibo();
    private Ventas V[]=new Ventas [1000];
    private int v=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxCredito;
    private javax.swing.JCheckBox cbxEfectivo;
    private javax.swing.JComboBox<String> cmbCedula;
    private javax.swing.JComboBox<String> cmbTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblBackground1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblMinimizar1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblSalir1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
